[tool.poetry]
name = "homework-21-2"
version = "0.1.0"
description = ""
authors = ["Svetlana Kalashnikova <serebsveta@rambler.ru>"]
readme = "README.md"
packages = [{include = "homework_21"}]

[tool.poetry.dependencies]
python = "^3.13"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
